language: node_js
node_js:
- '6'
- '6.1'
script:
- echo "deploy-o-matic"
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  region: us-west-2
  bucket: civicpdx.org
  skip_cleanup: true
  local_dir: dist
